version: 2
jobs:
  build:
    working_directory: ~/uderzo
    docker:
      - image: cdegroot/uderzo-ci:504214a
    steps:
      - checkout
      - run: source ~/.asdf/asdf.sh && make setup
      - save_cache:
          key: asdf
          paths:
            - "~/.asdf"
      - run: source ~/.asdf/asdf.sh && make deps test
